// Lookups into the responsive photo library generated by `npm run images`
// (scripts/optimize-images.mjs → public/images/library + src/data/image-library.json).
import library from '../data/image-library.json';
import { withBase } from './paths.ts';

export type LibraryImageId = keyof typeof library;

type Entry = { widths: number[]; width: number; height: number };

export function libraryEntry(id: LibraryImageId): Entry {
	const entry = (library as Record<string, Entry>)[id];
	if (!entry) throw new Error(`Unknown library image "${id}" — add it to scripts/image-manifest.mjs and run npm run images`);
	return entry;
}

/** URL of one rendition. Picks the smallest width >= `minWidth`, else the largest. */
export function imageUrl(id: LibraryImageId, minWidth = 1600): string {
	const { widths } = libraryEntry(id);
	const width = widths.find((w) => w >= minWidth) ?? widths.at(-1)!;
	return withBase(`/images/library/${id}-${width}.webp`);
}

/** 1200x630 JPEG social preview for a library image (pass to a layout's `image` prop). */
export function ogImageUrl(id: LibraryImageId): string {
	libraryEntry(id);
	return withBase(`/images/og/${id}.jpg`);
}

export function imageSrcset(id: LibraryImageId): string {
	return libraryEntry(id)
		.widths.map((w) => `${withBase(`/images/library/${id}-${w}.webp`)} ${w}w`)
		.join(', ');
}
